export const DEFAULT_CHATBOT_AI_DISCLOSURE =
  "Answers from {name} are generated by AI and may contain mistakes. Check important information.";

export const DEFAULT_DOC_SEARCH_AI_DISCLOSURE =
  "This summary was generated by AI and may contain mistakes. Check important information.";

export const formatAiDisclosure = (template: string, name: string): string =>
  template.split("{name}").join(name);
