import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const CHATBOT_DISCLOSURE =
  "Answers from {name} are generated by AI and may contain mistakes. Check important information.";
const DOC_SEARCH_DISCLOSURE =
  "This summary was generated by AI and may contain mistakes. Check important information.";
const MODEL_CAPABILITY_ERROR =
  "The configured AI model does not support image attachments. Contact the site administrator.";

const importTypeScript = async (fileUrl: URL) => {
  const source = await fs.readFile(fileUrl, "utf8");
  const compiled = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.ESNext,
      target: ts.ScriptTarget.ES2022,
    },
  }).outputText;
  return import(
    `data:text/javascript;base64,${Buffer.from(compiled).toString("base64")}`
  );
};

test("formats every chatbot name placeholder", async () => {
  const disclosures = await importTypeScript(
    new URL("../../core/src/ai-disclosures.ts", import.meta.url),
  );

  assert.equal(disclosures.DEFAULT_CHATBOT_AI_DISCLOSURE, CHATBOT_DISCLOSURE);
  assert.equal(
    disclosures.formatAiDisclosure("{name}: ask {name}", "Support Bot"),
    "Support Bot: ask Support Bot",
  );
});

test("all supported languages contain alphabetized AI disclosures", async () => {
  const directory = fileURLToPath(new URL("../src/i18n", import.meta.url));
  const files = (await fs.readdir(directory))
    .filter((file) => file.endsWith(".ts") && file !== "index.ts")
    .sort();

  assert.equal(files.length, 22);

  for (const file of files) {
    const module = await importTypeScript(
      new URL(`../src/i18n/${file}`, import.meta.url),
    );
    const dictionary = Object.values(module).find(
      (value) => typeof value === "object" && value !== null,
    ) as Record<string, string> | undefined;

    assert.ok(dictionary, `${file} must export a dictionary`);
    assert.ok(
      dictionary[CHATBOT_DISCLOSURE]?.includes("{name}"),
      `${file} must preserve the chatbot name placeholder`,
    );
    assert.ok(
      dictionary[DOC_SEARCH_DISCLOSURE]?.trim(),
      `${file} must translate the DocSearch disclosure`,
    );
    assert.ok(
      dictionary[MODEL_CAPABILITY_ERROR]?.trim(),
      `${file} must translate the model capability error`,
    );

    const keys = Object.keys(dictionary);
    assert.equal(
      keys.indexOf(CHATBOT_DISCLOSURE),
      keys.indexOf("An unknown error occurred.") + 1,
      `${file} must keep the chatbot disclosure alphabetized`,
    );
    assert.equal(
      keys.indexOf(DOC_SEARCH_DISCLOSURE),
      keys.indexOf("Title") - 1,
      `${file} must keep the DocSearch disclosure alphabetized`,
    );
    assert.equal(
      keys.indexOf(MODEL_CAPABILITY_ERROR),
      keys.indexOf("The caption for the image.") + 1,
      `${file} must keep the model capability error alphabetized`,
    );
  }
});

test("renders the chatbot disclosure beside status and outside the composer box", async () => {
  const component = await fs.readFile(
    new URL("../src/ai-chatbot/AiChatbot.tsx", import.meta.url),
    "utf8",
  );
  const statusIndex = component.indexOf('className="ai-status-line"');
  const disclosureIndex = component.indexOf(
    'className="ai-generated-content-disclosure ai-chatbot-generated-content-disclosure"',
  );
  const composerIndex = component.indexOf(
    '<Stack className="ai-box ai-box-open">',
  );

  assert.ok(statusIndex >= 0, "chatbot status line must be rendered");
  assert.ok(disclosureIndex > statusIndex, "disclosure must follow status");
  assert.ok(
    composerIndex > disclosureIndex,
    "disclosure must be outside and above the composer box",
  );
});

test("keeps chatbot image attachments explicitly opt-in", async () => {
  const component = await fs.readFile(
    new URL("../src/ai-chatbot/AiChatbot.tsx", import.meta.url),
    "utf8",
  );

  assert.match(component, /const DEFAULT_MAX_IMAGES = 0;/);
  assert.match(
    component,
    /const imageAttachmentsEnabled = resolvedMaxImages > 0;/,
  );
  assert.match(
    component,
    /const selectedImages = imageAttachmentsEnabled[\s\S]*?composerImagesRef\.current[\s\S]*?: \[\];/,
  );
  assert.match(component, /\{imageAttachmentsEnabled && \(/);
});
